# This is a basic workflow to help you get started with Actions
on:
  pull_request:
    branches: [ main ]


jobs:
  build:
    env:
      working-directory: ./app
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 14.16.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: Install dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}
        
      - name: Build
        run: npm run build:ci
        working-directory: ${{env.working-directory}}

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: coverage

